version: "3.8"

volumes:
  database_volume:

services:
  db_service:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: library
    volumes:
      - database_volume:/data/db
    ports:
      - "27018:27017"

  api_service:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db_service
    volumes:
      - .:/service
    command: uvicorn app.entry:service --host 0.0.0.0 --port 8000 --reload